# Python入门
>任何一种计算机语音，我们都需要搞明白它最基本的元素和基本的语法规则，可以先根据这个笔记简单的过一下

### 科学计算

In [10]:
print(2+2)
print(2*2)
print(2.0*2)
print(2**3)
print(2/3)
print(2**(1/2))
import math
print(math.sqrt(2))

4
4
4.0
8
0.6666666666666666
1.4142135623730951
1.4142135623730951


In [5]:
# 指数运算
import math
for x,y in [(2,3),(2.1,3.2),(1.0,5),(2.0,0),(2,float('nan')),(9.0,0.5),(27.0,1.0/3)]:
    print (x,y,math.pow(x,y))

2 3 8.0
2.1 3.2 10.74241047739471
1.0 5 1.0
2.0 0 1.0
2 nan nan
9.0 0.5 3.0
27.0 0.3333333333333333 3.0


In [12]:
# 对数运算
import math
print(math.log(8,2))

3.0


* 任何一种计算机语言中都要注意整数运算和浮点运算的区别

### 字符串

In [13]:
a = 2
a

2

In [24]:
s1 = "miner"
s2 = 'miner'
print(s1, s2)
s3 = """
hello
huahui
"""
s4 = '''
hello
huahui
'''
print(s3, s4)

# 字符串加法
s5 = s1+":"+s4
print(s5)
# 字符串索引
print(s1[0])
print(s1[-1])
print(s1[0:5])
# 字符串分割
s6 = s5.split()
print(s6)
# 字符串长度
print(len(s1))
print(len(s6))

miner miner

hello
huahui
 
hello
huahui

miner:
hello
huahui

m
r
miner
['miner:', 'hello', 'huahui']
5
3


***
* python中的变量赋值用 = 
* 字符串的单引号和双引号是等价的
* 字符串的三引号可加入多行文字
* 注意索引是从0开始，是个左闭右开的区间，所以最后一位其实没有对应的字符


### 列表和集合

In [28]:
a = [1,2,3,"a",1*2*3]
print(a)
print(a + a)
print(a[1])
print(len(a))
a.append("miner")
print(a)

[1, 2, 3, 'a', 6]
[1, 2, 3, 'a', 6, 1, 2, 3, 'a', 6]
2
5
[1, 2, 3, 'a', 6, 'miner']


In [37]:
b = {1,2,3,"a",2}
print(b)
print(len(b))
b.add("b")
print(b)
c = {1,2,"c"}
print(b & c)
print(b | c)
print(b - c)
print(b^c)

{1, 2, 3, 'a'}
4
{1, 2, 3, 'a', 'b'}
{1, 2}
{1, 2, 3, 'a', 'b', 'c'}
{3, 'a', 'b'}
{3, 'a', 'b', 'c'}


* 列表是[], 集合是{}
* 集合中不能有相同的元素
* 集合的交（&）并（|）差（-）对称差（^）

### 字典

In [42]:
dir = {'name': "huahui", 'age':5}
print(dir)
print(len(dir))
print(dir['name'])
# 修改
dir['name'] = 'miner'
print(dir)
# 插入
dir['gender'] = "famale"
print(dir)
# 获取键
print(dir.keys())
# 获取值
print(dir.values())
# all
print(dir.items())

{'name': 'huahui', 'age': 5}
2
huahui
{'name': 'miner', 'age': 5}
{'name': 'miner', 'age': 5, 'gender': 'famale'}
dict_keys(['name', 'age', 'gender'])
dict_values(['miner', 5, 'famale'])
dict_items([('name', 'miner'), ('age', 5), ('gender', 'famale')])


* python中很重要的一种数据形式：字典，主要由key(键)和value(值)组成
* 类比于其他语言中的hash表

### 数组

In [2]:
from numpy import array
a = array([1, 2, 3, 4])
print(a)
print(a + 2)
print(a + a)

[1 2 3 4]
[3 4 5 6]
[2 4 6 8]


* python很多情况下都要借助于包来实现具体的方法import  packages as pa 或者导入具体的方法 from packages import method
* 数组运算很方便实现某些循环

### 循环

In [6]:
a = [1, 2, 3, 4, 5, 6]
total = 0
for i in a:
    print(i)
    total+=int(i)
    print(total)

1
1
2
3
3
6
4
10
5
15
6
21


In [19]:
a = range(1,10,2)
for i in a:
    print(i)

1
3
5
7
9


In [29]:
a = range(1, 100, 2)
print(sum(range(1,101)))
total = sum([int(i) for i in a])
print(total)

5050
2500


In [ ]:
while True:
    word = input('please input a word:')
    if not word: break
    print('the word was ' + word

### 判断